using NFive.SDK.Core.Controllers;
using NFive.SDK.Core.Models;
using System.Collections.Generic;

namespace Addemod.IPLLoader.Shared {
	public class Configuration : ControllerConfiguration {
		public List<IPL> ipls { get; set; } = new List<IPL> {
			// METH LAB
			new IPL {
				InteriorProps = new List<InteriorProp> {
					//new InteriorProp { Name = "meth_lab_basic" },
					//new InteriorProp { Name = "meth_lab_empty" },
					//new InteriorProp { Name = "meth_lab_production" },
					new InteriorProp {
						Name = "meth_lab_security_high"
					},
					//new InteriorProp { Name = "meth_lab_setup" },
					new InteriorProp {
						Name = "meth_lab_upgrade"
					}
				},
				Locations = new List<Vector3> {
					new Vector3 {
						X = 1009.5f,
						Y = -3196.6f,
						Z = -38.99682f
					}
				}
			},
			
			// WEED LAB
			new IPL {
				InteriorProps = new List<InteriorProp> {
					new InteriorProp {
						Name = "weed_drying"
					},
					new InteriorProp { Name = "weed_production" },
					//new InteriorProp { Name = "weed_set_up" },
					//new InteriorProp { Name = "weed_standard_equip" },
					new InteriorProp { Name = "weed_upgrade_equip" },
					//new InteriorProp { Name = "weed_growtha_stage1" },
					//new InteriorProp { Name = "weed_growtha_stage2" },
					new InteriorProp { Name = "weed_growtha_stage3" },
					//new InteriorProp { Name = "weed_growthb_stage1" },
					//new InteriorProp { Name = "weed_growthb_stage2" },
					//new InteriorProp { Name = "weed_growthb_stage3" },
					new InteriorProp { Name = "weed_growthc_stage1" },
					//new InteriorProp { Name = "weed_growthc_stage2" },
					//new InteriorProp { Name = "weed_growthc_stage3" },
					new InteriorProp { Name = "weed_growthd_stage1" },
					//new InteriorProp { Name = "weed_growthd_stage2" },
					//new InteriorProp { Name = "weed_growthd_stage3" },
					//new InteriorProp { Name = "weed_growthe_stage1" },
					new InteriorProp { Name = "weed_growthe_stage2" },
					//new InteriorProp { Name = "weed_growthe_stage3" },
					//new InteriorProp { Name = "weed_growthf_stage1" },
					new InteriorProp { Name = "weed_growthf_stage2" },
					//new InteriorProp { Name = "weed_growthf_stage3" },
					new InteriorProp { Name = "weed_growthg_stage1" },
					//new InteriorProp { Name = "weed_growthg_stage2" },
					//new InteriorProp { Name = "weed_growthg_stage3" },
					//new InteriorProp { Name = "weed_growthh_stage1" },
					//new InteriorProp { Name = "weed_growthh_stage2" },
					new InteriorProp { Name = "weed_growthh_stage3" },
					//new InteriorProp { Name = "weed_growthi_stage1" },
					new InteriorProp { Name = "weed_growthi_stage2" },
					//new InteriorProp { Name = "weed_growthi_stage3" },
					new InteriorProp { Name = "weed_hosea" },
					new InteriorProp { Name = "weed_hoseb" },
					new InteriorProp { Name = "weed_hosec" },
					new InteriorProp { Name = "weed_hosed" },
					new InteriorProp { Name = "weed_hosee" },
					new InteriorProp { Name = "weed_hosef" },
					new InteriorProp { Name = "weed_hoseg" },
					new InteriorProp { Name = "weed_hoseh" },
					new InteriorProp { Name = "weed_hosei" },
					//new InteriorProp { Name = "light_growtha_stage23_standard" },
					//new InteriorProp { Name = "light_growthb_stage23_standard" },
					//new InteriorProp { Name = "light_growthc_stage23_standard" },
					//new InteriorProp { Name = "light_growthd_stage23_standard" },
					//new InteriorProp { Name = "light_growthe_stage23_standard" },
					//new InteriorProp { Name = "light_growthf_stage23_standard" },
					//new InteriorProp { Name = "light_growthg_stage23_standard" },
					//new InteriorProp { Name = "light_growthh_stage23_standard" },
					//new InteriorProp { Name = "light_growthi_stage23_standard" },
					new InteriorProp { Name = "light_growtha_stage23_upgrade" },
					new InteriorProp { Name = "light_growthb_stage23_upgrade" },
					new InteriorProp { Name = "light_growthc_stage23_upgrade" },
					new InteriorProp { Name = "light_growthc_stage23_upgrade" },
					new InteriorProp { Name = "light_growthd_stage23_upgrade" },
					new InteriorProp { Name = "light_growthe_stage23_upgrade" },
					new InteriorProp { Name = "light_growthf_stage23_upgrade" },
					new InteriorProp { Name = "light_growthg_stage23_upgrade" },
					new InteriorProp { Name = "light_growthh_stage23_upgrade" },
					new InteriorProp { Name = "light_growthi_stage23_upgrade" },
					//new InteriorProp { Name = "weed_low_security" },
					new InteriorProp { Name = "weed_security_upgrade" },
					new InteriorProp { Name = "weed_chairs" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 1051.491f, Y = -3196.536f, Z = -39.14842f } }
			},

			// Cocaine LAB
			new IPL {
				InteriorProps = new List<InteriorProp> {
					//new InteriorProp { Name = "security_low" },
					new InteriorProp { Name = "security_high" },
					new InteriorProp { Name = "equipment_basic" },
					new InteriorProp { Name = "equipment_upgrade" },
					//new InteriorProp { Name = "set_up" },
					//new InteriorProp { Name = "production_basic" },
					new InteriorProp { Name = "production_upgrade" },
					//new InteriorProp { Name = "table_equipment" },
					new InteriorProp { Name = "table_equipment_upgrade" },
					//new InteriorProp { Name = "coke_press_basic" },
					new InteriorProp { Name = "coke_press_upgrade" },
					new InteriorProp { Name = "coke_cut_01" },
					new InteriorProp { Name = "coke_cut_02" },
					new InteriorProp { Name = "coke_cut_03" },
					new InteriorProp { Name = "coke_cut_04" },
					new InteriorProp { Name = "coke_cut_05" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 1093.6f, Y = -3196.6f, Z = -38.99841f } }
			},

			// BUNKERS
			new IPL {
				InteriorProps = new List<InteriorProp> {
					//new InteriorProp { Name = "Bunker_Style_A" },
					//new InteriorProp { Name = "Bunker_Style_B" },
					new InteriorProp { Name = "Bunker_Style_C" },
					//new InteriorProp { Name = "standard_bunker_set" },
					new InteriorProp { Name = "upgrade_bunker_set" },
					//new InteriorProp { Name = "standard_security_set" },
					new InteriorProp { Name = "security_upgrade" },
					//new InteriorProp { Name = "Office_blocker_set" },
					new InteriorProp { Name = "Office_Upgrade_set" },
					//new InteriorProp { Name = "gun_range_blocker_set" },
					new InteriorProp { Name = "gun_wall_blocker" },
					new InteriorProp { Name = "gun_range_lights" },
					new InteriorProp { Name = "gun_locker_upgrade" },
					new InteriorProp { Name = "Gun_schematic_set" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 899.5518f, Y = -3246.038f, Z = -98.04907f } }
			},

			// FIB Lobby
			new IPL {
				InteriorProps = new List<InteriorProp> {
					new InteriorProp { Name = "V_FIB03_door_light" },
					new InteriorProp { Name = "V_FIB02_set_AH3b" },
					new InteriorProp { Name = "V_FIB03_set_AH3b" },
					new InteriorProp { Name = "V_FIB04_set_AH3b" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 110.4f, Y = -744.2f, Z = 45.7496f } }
			},

			// Counterfeit Cash Factory
			new IPL {
				InteriorProps = new List<InteriorProp> {
					//new InteriorProp { Name = "counterfeit_cashpile10a" },
					//new InteriorProp { Name = "counterfeit_cashpile10b" },
					//new InteriorProp { Name = "counterfeit_cashpile10c" },
					new InteriorProp { Name = "counterfeit_cashpile10d" },
					//new InteriorProp { Name = "counterfeit_cashpile20a" },
					//new InteriorProp { Name = "counterfeit_cashpile20b" },
					//new InteriorProp { Name = "counterfeit_cashpile20c" },
					new InteriorProp { Name = "counterfeit_cashpile20d" },
					//new InteriorProp { Name = "counterfeit_cashpile100a" },
					//new InteriorProp { Name = "counterfeit_cashpile100b" },
					//new InteriorProp { Name = "counterfeit_cashpile100c" },
					new InteriorProp { Name = "counterfeit_cashpile100d" },
					//new InteriorProp { Name = "counterfeit_low_security" },
					new InteriorProp { Name = "counterfeit_security" },
					//new InteriorProp { Name = "counterfeit_setup" },
					//new InteriorProp { Name = "counterfeit_standard_equip" },
					//new InteriorProp { Name = "counterfeit_standard_equip_no_prod" },
					new InteriorProp { Name = "counterfeit_upgrade_equip" },
					//new InteriorProp { Name = "counterfeit_upgrade_equip_no_prod" },
					new InteriorProp { Name = "money_cutter" },
					new InteriorProp { Name = "special_chairs" },
					//new InteriorProp { Name = "dryera_off" },
					new InteriorProp { Name = "dryera_on" },
					new InteriorProp { Name = "dryera_open" },
					//new InteriorProp { Name = "dryerb_off" },
					new InteriorProp { Name = "dryerb_on" },
					new InteriorProp { Name = "dryerb_open" },
					//new InteriorProp { Name = "dryerc_off" },
					new InteriorProp { Name = "dryerc_on" },
					new InteriorProp { Name = "dryerc_open" },
					//new InteriorProp { Name = "dryerd_off" },
					new InteriorProp { Name = "dryerd_on" },
					new InteriorProp { Name = "dryerd_open" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 1121.897f, Y = -3195.338f, Z = -40.4025f } }
			},

			// CLUBHOUSE 1
			new IPL {
				InteriorProps = new List<InteriorProp> {
					//new InteriorProp { Name = "cash_stash1" },
					//new InteriorProp { Name = "cash_stash2" },
					new InteriorProp { Name = "cash_stash3" },
					//new InteriorProp { Name = "coke_stash1" },
					//new InteriorProp { Name = "coke_stash2" },
					new InteriorProp { Name = "coke_stash3" },
					//new InteriorProp { Name = "counterfeit_stash1" },
					//new InteriorProp { Name = "counterfeit_stash2" },
					new InteriorProp { Name = "counterfeit_stash3" },
					//new InteriorProp { Name = "weed_stash1" },
					//new InteriorProp { Name = "weed_stash2" },
					new InteriorProp { Name = "weed_stash3" },
					//new InteriorProp { Name = "id_stash1" },
					//new InteriorProp { Name = "id_stash2" },
					new InteriorProp { Name = "id_stash3" },
					//new InteriorProp { Name = "meth_stash1" },
					//new InteriorProp { Name = "meth_stash2" },
					new InteriorProp { Name = "meth_stash3" },
					//new InteriorProp { Name = "decorative_01" },
					new InteriorProp { Name = "decorative_02" },
					//new InteriorProp { Name = "furnishings_01" },
					new InteriorProp { Name = "furnishings_02" },
					//new InteriorProp { Name = "walls_01" },
					new InteriorProp { Name = "walls_02" },
					//new InteriorProp { Name = "mural_01" },
					//new InteriorProp { Name = "mural_02" },
					//new InteriorProp { Name = "mural_03" },
					//new InteriorProp { Name = "mural_04" },
					//new InteriorProp { Name = "mural_05" },
					//new InteriorProp { Name = "mural_06" },
					//new InteriorProp { Name = "mural_07" },
					//new InteriorProp { Name = "mural_08" },
					new InteriorProp { Name = "mural_09" },
					new InteriorProp { Name = "gun_locker" },
					new InteriorProp { Name = "mod_booth" },
					//new InteriorProp { Name = "no_gun_locker" },
					//new InteriorProp { Name = "no_mod_booth" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 1107.04f, Y = -3157.399f, Z = -37.51859f } }
			},

			// CLUBHOUSE 2
			new IPL {
				InteriorProps = new List<InteriorProp> {
					new InteriorProp { Name = "cash_large" },
					//new InteriorProp { Name = "cash_medium" },
					//new InteriorProp { Name = "cash_small" },
					new InteriorProp { Name = "coke_large" },
					//new InteriorProp { Name = "coke_medium" },
					//new InteriorProp { Name = "coke_small" },
					new InteriorProp { Name = "counterfeit_large" },
					//new InteriorProp { Name = "counterfeit_medium" },
					//new InteriorProp { Name = "counterfeit_small" },
					new InteriorProp { Name = "id_large" },
					//new InteriorProp { Name = "id_medium" },
					//new InteriorProp { Name = "id_small" },
					new InteriorProp { Name = "meth_large" },
					//new InteriorProp { Name = "meth_medium" },
					//new InteriorProp { Name = "meth_small" },
					new InteriorProp { Name = "weed_large" },
					//new InteriorProp { Name = "weed_medium" },
					//new InteriorProp { Name = "weed_small" },
					//new InteriorProp { Name = "decorative_01" },
					new InteriorProp { Name = "decorative_02" },
					//new InteriorProp { Name = "furnishings_01" },
					new InteriorProp { Name = "furnishings_02" },
					//new InteriorProp { Name = "walls_01" },
					new InteriorProp { Name = "walls_02" },
					new InteriorProp { Name = "lower_walls_default" },
					new InteriorProp { Name = "gun_locker" },
					new InteriorProp { Name = "mod_booth" },
					//new InteriorProp { Name = "no_gun_locker" },
					//new InteriorProp { Name = "no_mod_booth" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 998.4809f, Y = -3164.711f, Z = -38.90733f } }
			},

			// IMPORT / EXPORT GARAGES
			new IPL {
				InteriorProps = new List<InteriorProp> {
					new InteriorProp { Name = "garage_decor_01" },
					new InteriorProp { Name = "garage_decor_02" },
					new InteriorProp { Name = "garage_decor_03" },
					new InteriorProp { Name = "garage_decor_04" },
					new InteriorProp { Name = "lighting_option01" },
					new InteriorProp { Name = "lighting_option02" },
					new InteriorProp { Name = "lighting_option03" },
					new InteriorProp { Name = "lighting_option04" },
					new InteriorProp { Name = "lighting_option05" },
					new InteriorProp { Name = "lighting_option06" },
					new InteriorProp { Name = "lighting_option07" },
					new InteriorProp { Name = "lighting_option08" },
					new InteriorProp { Name = "lighting_option09" },
					//new InteriorProp { Name = "numbering_style01_n1" },
					//new InteriorProp { Name = "numbering_style01_n2" },
					new InteriorProp { Name = "numbering_style01_n3" },
					//new InteriorProp { Name = "numbering_style02_n1" },
					//new InteriorProp { Name = "numbering_style02_n2" },
					new InteriorProp { Name = "numbering_style02_n3" },
					//new InteriorProp { Name = "numbering_style03_n1" },
					//new InteriorProp { Name = "numbering_style03_n2" },
					new InteriorProp { Name = "numbering_style03_n3" },
					//new InteriorProp { Name = "numbering_style04_n1" },
					//new InteriorProp { Name = "numbering_style04_n2" },
					new InteriorProp { Name = "numbering_style04_n3" },
					//new InteriorProp { Name = "numbering_style05_n1" },
					//new InteriorProp { Name = "numbering_style05_n2" },
					new InteriorProp { Name = "numbering_style05_n3" },
					//new InteriorProp { Name = "numbering_style06_n1" },
					//new InteriorProp { Name = "numbering_style06_n2" },
					new InteriorProp { Name = "numbering_style06_n3" },
					//new InteriorProp { Name = "numbering_style07_n1" },
					//new InteriorProp { Name = "numbering_style07_n2" },
					new InteriorProp { Name = "numbering_style07_n3" },
					//new InteriorProp { Name = "numbering_style08_n1" },
					//new InteriorProp { Name = "numbering_style08_n2" },
					new InteriorProp { Name = "numbering_style08_n3" },
					//new InteriorProp { Name = "numbering_style09_n1" },
					//new InteriorProp { Name = "numbering_style09_n2" },
					new InteriorProp { Name = "numbering_style09_n3" },
					new InteriorProp { Name = "floor_vinyl_01" },
					new InteriorProp { Name = "floor_vinyl_02" },
					new InteriorProp { Name = "floor_vinyl_03" },
					new InteriorProp { Name = "floor_vinyl_04" },
					new InteriorProp { Name = "floor_vinyl_05" },
					new InteriorProp { Name = "floor_vinyl_06" },
					new InteriorProp { Name = "floor_vinyl_07" },
					new InteriorProp { Name = "floor_vinyl_08" },
					new InteriorProp { Name = "floor_vinyl_09" },
					new InteriorProp { Name = "floor_vinyl_10" },
					new InteriorProp { Name = "floor_vinyl_11" },
					new InteriorProp { Name = "floor_vinyl_12" },
					new InteriorProp { Name = "floor_vinyl_13" },
					new InteriorProp { Name = "floor_vinyl_14" },
					new InteriorProp { Name = "floor_vinyl_15" },
					new InteriorProp { Name = "floor_vinyl_16" },
					new InteriorProp { Name = "floor_vinyl_17" },
					new InteriorProp { Name = "floor_vinyl_18" },
					new InteriorProp { Name = "floor_vinyl_19" },
					//new InteriorProp { Name = "basic_style_set" },
					//new InteriorProp { Name = "branded_style_set" },
					new InteriorProp { Name = "urban_style_set" },
					new InteriorProp { Name = "car_floor_hatch" },
					new InteriorProp { Name = "door_blocker" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 994.5925f, Y = -3002.594f, Z = -39.64699f } }
			},

			// CEO OFFICES
			new IPL {
				InteriorProps = new List<InteriorProp> {
					//new InteriorProp { Name = "cash_set_01" },
					//new InteriorProp { Name = "cash_set_02" },
					//new InteriorProp { Name = "cash_set_03" },
					//new InteriorProp { Name = "cash_set_04" },
					//new InteriorProp { Name = "cash_set_05" },
					//new InteriorProp { Name = "cash_set_06" },
					//new InteriorProp { Name = "cash_set_07" },
					//new InteriorProp { Name = "cash_set_08" },
					//new InteriorProp { Name = "cash_set_09" },
					//new InteriorProp { Name = "cash_set_10" },
					//new InteriorProp { Name = "cash_set_11" },
					//new InteriorProp { Name = "cash_set_12" },
					//new InteriorProp { Name = "cash_set_13" },
					//new InteriorProp { Name = "cash_set_14" },
					//new InteriorProp { Name = "cash_set_15" },
					//new InteriorProp { Name = "cash_set_16" },
					//new InteriorProp { Name = "cash_set_17" },
					//new InteriorProp { Name = "cash_set_18" },
					//new InteriorProp { Name = "cash_set_19" },
					//new InteriorProp { Name = "cash_set_20" },
					//new InteriorProp { Name = "cash_set_21" },
					//new InteriorProp { Name = "cash_set_22" },
					//new InteriorProp { Name = "cash_set_23" },
					//new InteriorProp { Name = "cash_set_24" },
					//new InteriorProp { Name = "office_booze" },
					new InteriorProp { Name = "office_chairs" },
					//new InteriorProp { Name = "swag_art" },
					//new InteriorProp { Name = "swag_art2" },
					new InteriorProp { Name = "swag_art3" },
					//new InteriorProp { Name = "swag_booze_cigs" },
					//new InteriorProp { Name = "swag_booze_cigs2" },
					//new InteriorProp { Name = "swag_booze_cigs3" },
					//new InteriorProp { Name = "swag_counterfeit" },
					//new InteriorProp { Name = "swag_counterfeit2" },
					new InteriorProp { Name = "swag_counterfeit3" },
					//new InteriorProp { Name = "swag_drugbags" },
					//new InteriorProp { Name = "swag_drugbags2" },
					//new InteriorProp { Name = "swag_drugbags3" },
					//new InteriorProp { Name = "swag_drugstatue" },
					//new InteriorProp { Name = "swag_drugstatue2" },
					//new InteriorProp { Name = "swag_drugstatue3" },
					//new InteriorProp { Name = "swag_electronic" },
					//new InteriorProp { Name = "swag_electronic2" },
					//new InteriorProp { Name = "swag_electronic3" },
					//new InteriorProp { Name = "swag_furcoats" },
					//new InteriorProp { Name = "swag_furcoats2" },
					//new InteriorProp { Name = "swag_furcoats3" },
					//new InteriorProp { Name = "swag_gems" },
					//new InteriorProp { Name = "swag_gems2" },
					//new InteriorProp { Name = "swag_gems3" },
					//new InteriorProp { Name = "swag_guns" },
					//new InteriorProp { Name = "swag_guns2" },
					//new InteriorProp { Name = "swag_guns3" },
					//new InteriorProp { Name = "swag_ivory" },
					//new InteriorProp { Name = "swag_ivory2" },
					//new InteriorProp { Name = "swag_ivory3" },
					//new InteriorProp { Name = "swag_jewelwatch" },
					new InteriorProp { Name = "swag_jewelwatch2" },
					//new InteriorProp { Name = "swag_jewelwatch3" },
					//new InteriorProp { Name = "swag_med" },
					//new InteriorProp { Name = "swag_med2" },
					//new InteriorProp { Name = "swag_med3" },
					//new InteriorProp { Name = "swag_pills" },
					//new InteriorProp { Name = "swag_pills2" },
					//new InteriorProp { Name = "swag_pills3" },
					//new InteriorProp { Name = "swag_silver" },
					//new InteriorProp { Name = "swag_silver2" },
					//new InteriorProp { Name = "swag_silver3" }
				},
				Locations = new List<Vector3> {
					new Vector3 { X = -141.1987f, Y = -620.913f, Z = 168.8205f },
					new Vector3 { X = -141.5429f, Y = -620.9524f, Z = 168.8204f },
					new Vector3 { X = -141.2896f, Y = -620.9618f, Z = 168.8204f },
					new Vector3 { X = -141.4966f, Y = -620.8292f, Z = 168.8204f },
					new Vector3 { X = -141.3997f, Y = -620.9006f, Z = 168.8204f },
					new Vector3 { X = -141.5361f, Y = -620.9186f, Z = 168.8204f },
					new Vector3 { X = -141.392f, Y = -621.0451f, Z = 168.8204f },
					new Vector3 { X = -141.1945f, Y = -620.8729f, Z = 168.8204f },
					new Vector3 { X = -141.4924f, Y = -621.0035f, Z = 168.8205f },
					new Vector3 { X = -75.8466f, Y = -826.9893f, Z = 243.3859f },
					new Vector3 { X = -75.49945f, Y = -827.05f, Z = 243.386f },
					new Vector3 { X = -75.49827f, Y = -827.1889f, Z = 243.386f },
					new Vector3 { X = -75.44054f, Y = -827.1487f, Z = 243.3859f },
					new Vector3 { X = -75.63942f, Y = -827.1022f, Z = 243.3859f },
					new Vector3 { X = -75.47446f, Y = -827.2621f, Z = 243.386f },
					new Vector3 { X = -75.56978f, Y = -827.1152f, Z = 243.3859f },
					new Vector3 { X = -75.51953f, Y = -827.0786f, Z = 243.3859f },
					new Vector3 { X = -75.41915f, Y = -827.1118f, Z = 243.3858f },
					new Vector3 { X = -1579.756f, Y = -565.0661f, Z = 108.523f },
					new Vector3 { X = -1579.678f, Y = -565.0034f, Z = 108.5229f },
					new Vector3 { X = -1579.583f, Y = -565.0399f, Z = 108.5229f },
					new Vector3 { X = -1579.702f, Y = -565.0366f, Z = 108.5229f },
					new Vector3 { X = -1579.643f, Y = -564.9685f, Z = 108.5229f },
					new Vector3 { X = -1579.681f, Y = -565.0003f, Z = 108.523f },
					new Vector3 { X = -1579.677f, Y = -565.0689f, Z = 108.5229f },
					new Vector3 { X = -1579.708f, Y = -564.9634f, Z = 108.5229f },
					new Vector3 { X = -1579.693f, Y = -564.8981f, Z = 108.5229f },
					new Vector3 { X = -1392.667f, Y = -480.4736f, Z = 72.04217f },
					new Vector3 { X = -1392.542f, Y = -480.4011f, Z = 72.04211f },
					new Vector3 { X = -1392.626f, Y = -480.4856f, Z = 72.04212f },
					new Vector3 { X = -1392.617f, Y = -480.6363f, Z = 72.04208f },
					new Vector3 { X = -1392.532f, Y = -480.7649f, Z = 72.04207f },
					new Vector3 { X = -1392.611f, Y = -480.5562f, Z = 72.04214f },
					new Vector3 { X = -1392.563f, Y = -480.549f, Z = 72.0421f },
					new Vector3 { X = -1392.528f, Y = -480.475f, Z = 72.04206f },
					new Vector3 { X = -1392.416f, Y = -480.7485f, Z = 72.04207f }
				}
			},

			// CEO GARAGES
			new IPL {
				InteriorProps = new List<InteriorProp> {
					//new InteriorProp { Name = "garage_decor_01" },
					//new InteriorProp { Name = "garage_decor_02" },
					//new InteriorProp { Name = "garage_decor_03" },
					new InteriorProp { Name = "garage_decor_04" },
					//new InteriorProp { Name = "lighting_option01" },
					//new InteriorProp { Name = "lighting_option02" },
					//new InteriorProp { Name = "lighting_option03" },
					//new InteriorProp { Name = "lighting_option04" },
					//new InteriorProp { Name = "lighting_option05" },
					//new InteriorProp { Name = "lighting_option06" },
					//new InteriorProp { Name = "lighting_option07" },
					//new InteriorProp { Name = "lighting_option08" },
					new InteriorProp { Name = "lighting_option09" },
					new InteriorProp { Name = "numbering_style01_n1" },
					//new InteriorProp { Name = "numbering_style01_n2" },
					//new InteriorProp { Name = "numbering_style01_n3" },
					new InteriorProp { Name = "numbering_style02_n1" },
					//new InteriorProp { Name = "numbering_style02_n2" },
					//new InteriorProp { Name = "numbering_style02_n3" },
					new InteriorProp { Name = "numbering_style03_n1" },
					//new InteriorProp { Name = "numbering_style03_n2" },
					//new InteriorProp { Name = "numbering_style03_n3" },
					new InteriorProp { Name = "numbering_style04_n1" },
					//new InteriorProp { Name = "numbering_style04_n2" },
					//new InteriorProp { Name = "numbering_style04_n3" },
					new InteriorProp { Name = "numbering_style05_n1" },
					//new InteriorProp { Name = "numbering_style05_n2" },
					//new InteriorProp { Name = "numbering_style05_n3" },
					new InteriorProp { Name = "numbering_style06_n1" },
					//new InteriorProp { Name = "numbering_style06_n2" },
					//new InteriorProp { Name = "numbering_style06_n3" },
					new InteriorProp { Name = "numbering_style07_n1" },
					//new InteriorProp { Name = "numbering_style07_n2" },
					//new InteriorProp { Name = "numbering_style07_n3" },
					new InteriorProp { Name = "numbering_style08_n1" },
					//new InteriorProp { Name = "numbering_style08_n2" },
					//new InteriorProp { Name = "numbering_style08_n3" },
					new InteriorProp { Name = "numbering_style09_n1" },
					//new InteriorProp { Name = "numbering_style09_n2" },
					//new InteriorProp { Name = "numbering_style09_n3" },
					new InteriorProp { Name = "basic_style_set" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 795.75439453125f, Y = -2997.3317871094f, Z = -22.960731506348f } }
			},

			// CEO VEHICLES SHOPS
			new IPL {
				InteriorProps = new List<InteriorProp> {
					//new InteriorProp { Name = "floor_vinyl_01" },
					//new InteriorProp { Name = "floor_vinyl_02" },
					new InteriorProp { Name = "floor_vinyl_03" },
					//new InteriorProp { Name = "floor_vinyl_04" },
					//new InteriorProp { Name = "floor_vinyl_05" },
					//new InteriorProp { Name = "floor_vinyl_06" },
					//new InteriorProp { Name = "floor_vinyl_07" },
					//new InteriorProp { Name = "floor_vinyl_08" },
					//new InteriorProp { Name = "floor_vinyl_09" },
					//new InteriorProp { Name = "floor_vinyl_10" },
					//new InteriorProp { Name = "floor_vinyl_11" },
					//new InteriorProp { Name = "floor_vinyl_12" },
					//new InteriorProp { Name = "floor_vinyl_13" },
					//new InteriorProp { Name = "floor_vinyl_14" },
					//new InteriorProp { Name = "floor_vinyl_15" },
					//new InteriorProp { Name = "floor_vinyl_16" },
					//new InteriorProp { Name = "floor_vinyl_17" },
					//new InteriorProp { Name = "floor_vinyl_18" },
					//new InteriorProp { Name = "floor_vinyl_19" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 730.63916015625f, Y = -2993.2373046875f, Z = -38.999904632568f } }
			},

			// BIKERS Document Forgery Office
			new IPL {
				InteriorProps = new List<InteriorProp> {
					new InteriorProp { Name = "chair01" },
					new InteriorProp { Name = "chair02" },
					new InteriorProp { Name = "chair03" },
					new InteriorProp { Name = "chair04" },
					new InteriorProp { Name = "chair05" },
					new InteriorProp { Name = "chair06" },
					new InteriorProp { Name = "chair07" },
					new InteriorProp { Name = "clutter" },
					//new InteriorProp { Name = "equipment_basic" },
					new InteriorProp { Name = "equipment_upgrade" },
					//new InteriorProp { Name = "interior_basic" },
					new InteriorProp { Name = "interior_upgrade" },
					new InteriorProp { Name = "production" },
					new InteriorProp { Name = "security_high" },
					//new InteriorProp { Name = "security_low" },
					new InteriorProp { Name = "set_up" }
				},
				Locations = new List<Vector3> { new Vector3 { X = 1163.842f, Y = -3195.7f, Z = -39.008f } }
			},

			// Doomsday Facility
			new IPL {
				InteriorProps = new List<InteriorProp> {
					new InteriorProp { Name = "set_int_02_decal_01", Color = 1 },
					new InteriorProp { Name = "set_int_02_lounge1", Color = 1 },
					new InteriorProp { Name = "set_int_02_cannon", Color = 1 },
					new InteriorProp { Name = "set_int_02_clutter1", Color = 1 },
					new InteriorProp { Name = "set_int_02_crewemblem" },
					new InteriorProp { Name = "set_int_02_shell", Color = 1 },
					new InteriorProp { Name = "set_int_02_security", Color = 1 },
					new InteriorProp { Name = "set_int_02_sleep", Color = 1 },
					new InteriorProp { Name = "set_int_02_trophy1", Color = 1 },
					new InteriorProp { Name = "set_int_02_paramedic_complete", Color = 1 },
					new InteriorProp { Name = "set_Int_02_outfit_paramedic", Color = 1 },
					new InteriorProp { Name = "set_Int_02_outfit_serverfarm", Color = 1 }
				},
				Locations = new List<Vector3> { new Vector3 { X = 483.2f, Y = 4810.5f, Z = -58.9f } }
			},

			// Smugglers Run Hangar
			new IPL {
				InteriorProps = new List<InteriorProp> {
					new InteriorProp { Name = "set_lighting_hangar_a" },
					new InteriorProp { Name = "set_lighting_hangar_a" },
					new InteriorProp { Name = "set_tint_shell", Color = 1 },
					new InteriorProp { Name = "set_bedroom_tint", Color = 1 },
					new InteriorProp { Name = "set_crane_tint", Color = 1 },
					new InteriorProp { Name = "set_modarea", Color = 1 },
					new InteriorProp { Name = "set_lighting_tint_props", Color = 1 },
					new InteriorProp { Name = "set_floor_1" },
					new InteriorProp { Name = "set_floor_decal_1", Color = 1 },
					new InteriorProp { Name = "set_bedroom_modern" },
					new InteriorProp { Name = "set_office_modern" },
					new InteriorProp { Name = "set_bedroom_blinds_open" },
					new InteriorProp { Name = "set_lighting_wall_tint01" }
				},
				Locations = new List<Vector3> { new Vector3 { X = -1266.0f, Y = -3014.0f, Z = -47.0f } }
			}
		};
	}
}
